select 
matches.match_status_for_match,
male."Age" as "Male_Age",female."Age" as "Female_Age",
male."Religious_orientation" as "Male_MemberData", 
female."Religious_orientation" as "Female_MemberData",
male."Frequency_of_Torah_study_male" as "Male_Frequency_of_Torah_study",
female."Dress_female" as "Female_Dress",
male."Family_religious_background" as "Male_Family_Background",
female."Family_religious_background" as "Female_Family_Background",
male."My_marriage_status" as "Male_Marriage_Status",
female."My_marriage_status" as "Female_Marriage_Status",
male."Political_orientation" as "Male_Political_Orientation",
female."Political_orientation" as "Female_Political_Orientation",
male."Introvert_Extravert" as "Male_Introvert_Extravert",
female."Introvert_Extravert" as "Female_Introvert_Extravert",
male."Sensor_Intuitive" as "Male_Sensor_Intuitive",
female."Sensor_Intuitive" as "Female_Sensor_Intuitive",
male."Thinker_Feeler" as "Male_Thinker_Feeler",
female."Thinker_Feeler" as "Female_Thinker_Feeler",
male."Judger_Perceiver" as "Male_Judger_Perceiver",
female."Judger_Perceiver" as "Female_Judger_Perceiver",
male."Minimum_Education_level" as "Male_Minimum_Education_level",
female."Minimum_Education_level" as "Female_Minimum_Education_level",
male."Jewish_education" as "Male_Jewish_Education",
female."Jewish_education" as "Female_Jewish_Education"
from matches
left join memberdata as male on matches.male_id = male."Member_ID"::integer
left join memberdata as female on matches.female_id = female."Member_ID"::integer
where row(
male."Age", 
female."Age",
male."Religious_orientation",
female."Religious_orientation",
male."Frequency_of_Torah_study_male",
female."Dress_female",
male."Family_religious_background",
female."Family_religious_background",
male."My_marriage_status",
female."My_marriage_status",
male."Political_orientation",
female."Political_orientation",
male."Introvert_Extravert",
female."Introvert_Extravert",
male."Sensor_Intuitive",
female."Sensor_Intuitive",
male."Thinker_Feeler",
female."Thinker_Feeler",
male."Judger_Perceiver",
female."Judger_Perceiver",
male."Minimum_Education_level",
female."Minimum_Education_level",
male."Jewish_education",
female."Jewish_education",
male."Profile_Last_modified_date",
female."Profile_Last_modified_date") IS NOT NULL;
